# Generated by Django 5.0.6 on 2024-08-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="start_date",
            field=models.DateField(),
        ),
    ]
