# Generated by Django 5.0.6 on 2024-08-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmailPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.EmailField(max_length=254, unique=True)),
                (
                    "recipe_preferences",
                    models.TextField(
                        help_text="Comma-separated list of selected cuisines"
                    ),
                ),
            ],
        ),
    ]
