# Generated by Django 5.0.6 on 2024-07-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_alter_post_banner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="banner",
            field=models.ImageField(blank=True, default="img2.png", upload_to=""),
        ),
    ]
