# Generated by Django 5.0.6 on 2024-08-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment_gateway", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="course",
            field=models.CharField(default="", max_length=50),
        ),
    ]
