# Generated by Django 5.0.6 on 2024-07-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="content_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="course",
            name="course_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
