# Generated by Django 5.0.6 on 2024-08-12 11:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0004_enrollment_transaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("expired", "Expired")],
                default="active",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="enrolled_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
