# Generated by Django 5.0.6 on 2024-08-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_content_updated_at_enrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
